config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'static_pages#home'

  #get 'static_pages/help'
  match '/help', to: 'static_pages#help', via: 'get'
  #get 'static_pages/about'
  match '/about', to: 'static_pages#about', via: 'get'
  #get 'static_pages/contact'
  match '/contact', to: 'static_pages#contact', via: 'get'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  #nameが入力されていないと許可しない設定。長さ制限５０文字
  #↓はvalidates(:name, presence: true)と同じ意味
  validates :name, presence: true, length: {maximum: 50 }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

###ブラウザ（ページ）のタイトル名表示を設定
 #page_titleが空の場合base_titleを表示
 #違う場合はbase_title | page_titleで表示する
  def full_title(page_title)
    base_title = "Ruby on Rails Tutotial"
      if page_title.empty? #empty?で配列が空であればtrue、1つ以上の要素があればfalseを返す
        base_title
      else
        "#{base_title} | #{page_title}"
      end
  end

###deviseの必要設定
 ##bootstrapでflashメッセージを表示する
  def bootstrap_class_for(flash_type)
    case flash_type
      when :success
        "alert-success"
      when :error
        "alert-danger"
      when :alert
        "alert-warning"
      when :notice
        "alert-info"
      else
        flash_type.to_s
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class = "footer">
  <small>
    <a href="http://railstutorial.org/">Rails Tutorial</a>
    by Michael Hartl
  </small>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li><!--リンクが「xxxx_path」になる時は''要らない-->
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<!--bootstrapを利用する場合は、クラス名で表示が変ってくるためクラス名が重要-->
<header class = "navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Rails App", root_path, id: "logo" %><!--ヘッダーにリンク付きロゴを作成-->
    <nav>
      <ul class = "nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li><!--リンクが「xxxx_path」になる時は''要らない-->
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "Sign in", '#' %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shiv.html.erb
<!--古いバーじょんIEでも表示できるように設定-->
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shiv' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <!--bootstrapのalert表示-->
      <% flash.each do |key, value| %>
        <div class="alert <%= bootstrap_class_for(key) %>"><%= value %></div>
      <% end %>
      <!--bootstrapのalert表示ここまで-->
          <%= yield %>
          <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<%= provide(:title, 'About Us') %>
<h1>About</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<%= provide(:title, 'Content') %>
<h1>Contact</h1>
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<%= provide(:title, 'Help') %>
<h1>Help</h1>
<p>
    Get help on the Ruby on Rails Tutorial at the
    <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
    To get help on this sample app, see the
    <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<div class = "center jumbotron">

    <h1>ようこそ　Rails Appへ</h1>
      <h2>
        This is the home page for the
        <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
        sample application.
      </h2>

      <%= link_to "Sign Up Now", '#', class: "btn btn-lg btn-primary" %>
</div>

<%= link_to image_tag("rails.png",alt: "Rails"), '#' %>